### ISSUE TITLE
mac address not changing

### ISSUE THREAD

**Issue by 7fqxj** [DavidBerdik/MACsposed#9]
my mac address was changing properly and a week ago it stoped changing,  I use samsung a21s android 12, stable magisk root

**Comment by DavidBerdik** [comment]
I suspect that this issue was caused by MACsposed v1.1.4. If you haven't already done so, could you please try upgrading to MACsposed v1.1.5 and try again?

Since this is probably the issue, I am going to mark this as closed, however, if you are still having issues after installing the latest version, please feel free to comment here so that I may reopen it.
